### PR TITLE
Feat/sticky node

### PR DESCRIPTION
**Pull request by xp1632**
StickyNote Node passed the following test case:

Test case:

1. Drag:
	-With no comments
	-With normal comments
	-With long comments
	
2. Input comments
	-Without background color
	-With Background color
	-With resize, check if the text would float out of border

3. Color Picker
	-Colored in correct area without resizing
	-Colored in correct area with resizing
	
4. Resize
	-does the node resize correctly?
	
5. Pinned function

	-Before editing, pinned, not dragable;unpinned, dragable
	-After editing,pinned, not dragable;unpinned, dragable

### CODE REVIEW

**Comment by Max-ChenFei** [comment]
Esc23

**Comment by xp1632** [comment]
Animation
Animation2

Fixed in [38a9710](https://github.com/Max-ChenFei/VisualProgrammingEditor/pull/195/commits/38a9710fbf3aedf82bbe2dcb53e53837557b2073)

**Comment by xp1632** [comment]
Animation3
Fix in [1f70771](https://github.com/Max-ChenFei/VisualProgrammingEditor/pull/195/commits/1f70771c01e1d9b5eca1938afc878e9ba780b51a)

**Comment by Max-ChenFei** [comment]
fixed Esc233

**Pull request merged**
